import json
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

# Global OCR text purifier for Turkish medical questions
def purify_text(text):
    if not text:
        return ""
    t = str(text)
    
    # Common OCR manglings
    replaces = [
        (r'Atai!Jidaki', 'Aşağıdaki'),
        (r'Ataı!Jıdakl', 'Aşağıdaki'),
        (r'a,a~ıdakJ', 'aşağıdaki'),
        (r'aıafııdakllerden', 'aşağıdakilerden'),
        (r'aşaöıdaki', 'aşağıdaki'),
        (r'AfaOıdakf', 'Aşağıdaki'),
        (r'Afağıdakl', 'Aşağıdaki'),
        (r'AşaQıdakl', 'Aşağıdaki'),
        (r'Aıağıdakl', 'Aşağıdaki'),
        (r'aşa ı a I', 'aşağıdaki'),
        (r'a,a\{ııdakl', 'aşağıdaki'),
        (r'Aşa{ııdakl', 'Aşağıdaki'),
        (r'A O d ki ıtadeletd&n', 'Aşağıdaki ifadelerden'),
        (r'Aşaö ıdakl', 'Aşağıdaki'),
        (r'aşığıda1d', 'aşağıdaki'),
        (r'aşa.ır. ıda kll d ~ er · en hangi ldlr\?', 'aşağıdakilerden hangisidir?'),
        (r'apC,ıclalcll _ rden hangisidir\?', 'aşağıdakilerden hangisidir?'),
        (r'leııfofd', 'lenfoid'),
        (r'lenfold', 'lenfoid'),
        (r'oroıınıarııı', 'organlarının'),
        (r'bylynm~z\?', 'bulunmaz?'),
        (r'\bnmus\b', 'Timus'),
        (r'Lenf dOOOmo', 'Lenf düğümü'),
        (r'Tonsıııa paıatına', 'Tonsilla palatina'),
        (r'Befincl', 'Beşinci'),
        (r'yanhıtır\?', 'yanlıştır?'),
        (r'~nhştır\?', 'yanlıştır?'),
        (r'Mitoük', 'Mitotik'),
        (r'Ç<>Oalmak', 'Çoğalmak'),
        (r'h0crelerini', 'hücrelerini'),
        (r'h0crelerlnl', 'hücrelerini'),
        (r'h0cre', 'hücre'),
        (r'h0kcrell 1', 'hücreli'),
        (r'\bONA\b', 'DNA'),
        (r'sltoplazma', 'sitoplazma'),
        (r'sltoJazm', 'sitoplazm'),
        (r'sitopJazmlJ<', 'sitoplazma'),
        (r'erltrold', 'eritroid'),
        (r'erltro', 'eritro'),
        (r'mltokondr', 'mitokondr'),
        (r'perlkard', 'perikard'),
        (r'mlyokar', 'miyokar'),
        (r'eplkard', 'epikard'),
        (r'subeplkard', 'subepikard'),
        (r'subencJotelyurn', 'Subendotelyum'),
        (r'Subeplkardlyum', 'Subepikardiyum'),
        (r'Subendokardlyum', 'Subendokardiyum'),
        (r'CamScanner[^\n]*', ''),
        (r'CamScanner ile tarandı', ''),
        (r'bOyOme', 'büyüme'),
        (r'kısıt1~1ığı', 'kısıtlılığı'),
        (r'OçOncO', 'Üçüncü'),
        (r'Oçanco', 'Üçüncü'),
        (r'aOrılı', 'ağrılı'),
        (r'görOlOr', 'görülür'),
        (r'görOIOr', 'görülür'),
        (r'özerlne', 'üzerine'),
        (r'yOzey', 'yüzey'),
        (r'mlkro', 'mikro'),
        (r'kllnlk', 'klinik'),
        (r'tOmOr', 'tümör'),
        (r'tomör', 'tümör'),
        (r'hlper', 'hiper'),
        (r'lnhib', 'inhib'),
        (r'lnakt', 'inakt'),
        (r'aktlv', 'aktiv'),
        (r'endoskoplsl', 'endoskopisi'),
        (r'dfstalde', 'distalde'),
        (r'ıomeninfn', 'lümeninin'),
        (r'uQradığı', 'uğradığı'),
        (r'slnlstra', 'sinistra'),
        (r'slnlstrum', 'sinistrum'),
        (r'Hlatus', 'Hiatus'),
        (r'pupllla', 'pupilla'),
        (r'calcarlnus', 'calcarinus'),
        (r'genlculatum', 'geniculatum'),
        (r'cillare', 'ciliare'),
        (r'dOğUmlerlnden', 'düğümlerinden'),
        (r'lngulnales', 'inguinales'),
        (r'profundl', 'profundi'),
        (r'illacl', 'iliaci'),
        (r'inteml', 'interni'),
        (r'superficlales', 'superficiales'),
        (r'Nadi', 'Nodi'),
        (r'etkllendlC,lnde', 'etkilendiğinde'),
        (r'dll ucu', 'dil ucu'),
        (r'\~•kartııamaz\?', 'çıkartılamaz?'),
        (r'genloglossus', 'genioglossus'),
        (r'genlohyoideus', 'geniohyoideus'),
        (r'fertlllzasyon', 'fertilizasyon'),
        (r'ills oluşan', 'ilk oluşan'),
        (r'·Trofoblast', 'Trofoblast'),
        (r'Epibfast', 'Epiblast'),
        (r'değildi\[\?', 'değildir?'),
        (r'kemik lll~lnde', 'kemik iliğinde'),
        (r'eksternal lamına', 'eksternal lamina'),
        (r'VentrikOler', 'Ventriküler'),
        (r'anomalllerlnden', 'anomalilerinden'),
        (r'hangllerl', 'hangileri'),
        (r'endokardlyal', 'endokardiyal'),
        (r'çıka r\?', 'çıkar?'),
        (r'bblfurkasyon', 'bifurkasyon'),
        (r'periferlk', 'periferik'),
        (r'hlpokapnl', 'hipokapni'),
        (r'Kandak\.i', 'Kandaki'),
        (r'ventllasyon', 'ventilasyon'),
        (r'\.d§ğlldlt\?', 'değildir?'),
        (r'Kanama ;:deni ~e ~~erl:y~chl olmayan şok tablosuyla acil servise getlrllen yaşın a er 8 astada', 
         'Kanama nedeniyle dekompanse olmayan şok tablosuyla acil servise getirilen 25 yaşındaki erkek hastada'),
        (r'Antldlüretlk', 'Antidiüretik'),
        (r'glukokortlkold', 'glukokortikoid'),
        (r'g\.öıleomez\?', 'gözlenmez?'),
        (r'Sltoplazmada', 'Sitoplazmada'),
        (r'mltokondrlyal', 'mitokondriyal'),
        (r'aşağı~aki', 'aşağıdaki'),
        (r'Sitozollk', 'Sitozolik'),
        (r'transamlnaz', 'transaminaz'),
        (r'transamlnasyonu', 'transaminasyonu'),
        (r'dehldrogenaz', 'dehidrogenaz'),
        (r'varciır\.', 'vardır.'),
        (r'Bir_protei_ni ~~d_layan ONA dizisindeki nokta mutasyonları sonucunda amıno asıt dızısınde oluşan,',
         'Bir proteini kodlayan DNA dizisindeki nokta mutasyonları sonucunda amino asit dizisinde oluşan;'),
        (r'~::a mdutadsyonıa~ından hangileri bu proteinin izoelektrik sın a eğlşlkflge neden olur\?',
         'Yukarıdaki mutasyonlardan hangileri bu proteinin izoelektrik noktasında (pI) değişikliğe neden olur?'),
        (r'lzofösin -+ Lizin', 'İzolösin → Lizin'),
        (r'Lösin -+ Fenilalanin', 'Lösin → Fenilalanin'),
        (r'Alanin -+ Glutamat', 'Alanin → Glutamat'),
        (r'besl~nme', 'beslenme'),
        (r'µmoVL', 'µmol/L'),
        (r'düzeyreri', 'düzeyleri'),
        (r'\.hangisinin', 'hangisinin'),
        (r'ayınca tanı', 'ayırıcı tanı'),
        (r'3-mefü-krotonilglisin', '3-metil-krotonilglisin'),
        (r'Homoslstein', 'Homosistein'),
        (r'Metionln', 'Metionin'),
        (r'metlonln', 'metionin'),
        (r'Sistatiyonin J3-sentaz', 'Sistatiyonin beta-sentaz'),
        (r'Pirldoksal', 'Piridoksal'),
        (r'ekslkllğlnde', 'eksikliğinde'),
        (r'aktlvlteslnde', 'aktivitesinde'),
        (r'bulanıklı\(jı', 'bulanıklığı'),
        (r'karaci\(jeri', 'karaciğer'),
        (r'0mitln karbamolltransferaz', 'ornitin transkarbamoilaz'),
        (r'ekslkllQi', 'eksikliği'),
        (r'a9aCııdakllerden', 'aşağıdakilerden'),
        (r'Glutamın', 'Glutamin'),
        (r'Dopamtn', 'Dopamin'),
        (r'Arglnin', 'Arginin'),
        (r'\~•daJd am!_no ~sitler~~~ hangisi ATP\'den adenozll alarak fosfor ıcenngyen yuksek enerJılı bileşik oluşturur\?',
         'Aşağıdaki amino asitlerden hangisi ATP\'den adenozil grubu alarak fosfor içermeyen yüksek enerjili bileşik oluşturur?'),
        (r'Alanın', 'Alanin'),
        (r'lirozjn', 'Tirozin'),
        (r'Sisteln', 'Sistein'),
        (r'MetJonln', 'Metionin'),
        (r'Histldln', 'Histidin'),
        (r'affinltesl', 'affinitesi'),
        (r'sşğa kaymıştır\.', 'sağa kaymıştır.'),
        (r'satorasyon', 'satürasyon'),
        (r'p\.O 2 azlıQına', 'pO2 azlığına'),
        (r'sat0rasyon', 'satürasyon'),
        (r'kardiyolipin', 'kardiyolipin'),
        (r'Fosfatidik asit', 'Fosfatidik asit'),
        (r'CDP-diaçilgliserol', 'CDP-diaçilgliserol'),
        (r'Per\\\\\\p\\n', 'Perilipin'),
        (r'protein \\\\\\naz A', 'Protein kinaz A'),
        (r'Apo C-\\\\', 'Apo C-II'),
        (r'G protelıı', 'G proteini'),
        (r'Termogen\\n', 'Termogenin'),
        (r'~tenin', 'Beta-katenin'),
        (r'COC4-', 'CDC4 -'),
        (r'İAXgenJ', 'BAX geni'),
        (r'Glutatyon 1\)', 'Glutatyon'),
        (r'N-asetıl-p-benzoquinon imin \(NAPQ', 'N-asetil-p-benzokinon imin (NAPQI)'),
        (r'Oimerkaprol', 'Dimerkaprol'),
        (r'HippOrik', 'Hippürik'),
        (r'SOperokslt', 'Süperoksit'),
        (r'Hldroksll', 'Hidroksil'),
        (r'Slnglet', 'Singlet'),
        (r'Llpld', 'Lipid'),
        (r'radlkall', 'radikali'),
        (r'tanımladnam~~~nşdaa', 'tanımlanmasında'),
        (r'asetoln', 'asetoin'),
        (r'lndol', 'İndol'),
        (r'Hema~\'\?li_k mallgnltesl olan ve ateş nedeniyle izlenen hastadan aıı~a;',
         'Hematolojik malignitesi olan ve ateş nedeniyle izlenen hastadan alınan'),
        (r'pasaJd · pamuOumsu', 'pasajda pamuksu'),
        (r'oredlQI göroıoyor', 'ürediği görülüyor'),
        (r'Kol~nlden', 'Koloniden'),
        (r'kano şeklıocte', 'kano şeklinde'),
        (r'makrokonldyumların varlıQı', 'makrokonidyumların varlığı'),
        (r'10 olası tanımıar11• aıafııdakllerden', 'en olası tanımlama aşağıdakilerden'),
        (r'hipe~rofi', 'hipertrofi'),
        (r'kardiyom~yopati', 'kardiyomiyopati'),
        (r'karacığer', 'karaciğer'),
        (r'~e~i~ıklıkler', 'değişiklikler'),
        (r'çızgılı', 'çizgili'),
        (r'GranDlom', 'Granülom'),
        (r'tDberkDloz', 'tüberküloz'),
        (r'fag~lizozomlara', 'fagolizozomlara'),
        (r'peroksinltrit', 'peroksinitrit'),
        (r'Anormal uterln :ıana I soşnucunda endometrioid tip endometriyu~ kadın hastanın yo~!\nıyor Soy geçmişinden annesinin genç Yaşta adenokatslnomu sap · öldü~0 öğreniliyor\. metastatik kolon kanseri sonucu ~ · \. 1 ö• Jlnone ahndıöırtda hastaya aşağıdaki hangi testin Bu bulgu arg \.\. u yapılmagı önerilir\?',
         'Anormal uterin kanama sonucunda endometrioid tip endometriyum adenokarsinomu saptanan kadın hastanın soy geçmişinden annesinin genç yaşta metastatik kolon kanseri sonucu öldüğü öğreniliyor. Bu bulgular göz önüne alındığında hastaya aşağıdaki hangi testin yapılması önerilir?'),
        (r'Altmış yaş~dakl :ot GörOntOleme tetkiklerinde, endometriyu;~e hastaneye aşvuru · d 8 cm çap ı nda kitle tespit edil\' a kalınlık art ı şı ile saO over 8 _ • k \.\. \'Yor\. - \. _ bl si materyalinde endometrıold arsınom saptana Endomettriyu\\ mi bdyoo~lnal hlsterekto~lnln yanıs ı ra bilateral salping"n hastaya o 8 8 hl t t · 1 "k · ı "\' ooforektoml uygulanıyor\. over kltleslnln_ s opa o oJı ınce emesinde yetişkin tip gtanOloza hücreli tomör lzlenıyor\. A O d ki ıtadeletd&n hangisi bu hastada endometrlyum ve overcıe 1ı:ien~n 8 t0mötlerln ilişkisini en iyi açıklar\?',
         'Altmış yaşındaki kadın hasta vajinal kanama şikayeti ile hastaneye başvuruyor. Görüntüleme tetkiklerinde endometriyal kalınlık artışı ile sağ overde 8 cm çapında kitle tespit ediliyor. Endometriyum biyopsi materyalinde endometrioid karsinom saptanan hastaya abdominal histerektominin yanı sıra bilateral salpingo-ooforektomi uygulanıyor. Over kitlesinin histopatolojik incelemesinde yetişkin tip granüloza hücreli tümör izleniyor. Aşağıdaki ifadelerden hangisi bu hastada endometriyum ve overde izlenen tümörlerin ilişkisini en iyi açıklar?'),
        (r'keratJn lntenn\.edlyer fllamanının', 'keratin intermedyer filamanının'),
        (r'varlı\(ımın g\'österllebUmesl', 'varlığının gösterilebilmesi'),
        (r'8tııöıdakJ yöntemlerden', 'aşağıdaki yöntemlerden'),
        (r'dıhı ıık', 'daha sık'),
        (r'Ftoresan in sltu hlbrldlzasyon', 'Floresan in situ hibridizasyon (FISH)'),
        (r'Southern blottlng', 'Southern blotting'),
        (r'Jmrnonohlsıc>klmy,a', 'İmmünohistokimya'),
        (r'\'\(eni nesli sekanslarna', 'Yeni nesil dizileme (NGS)'),
        (r'Revers tr~nskrlptez pollmeraz zincir reaksiyonu', 'RT-PCR'),
        (r'GörOntOdekl', 'Görüntüdeki'),
        (r'patogenezloda aıaöıdakllerden', 'patogenezinde aşağıdakilerden'),
        (r'serbest yaQ asitlerinin', 'serbest yağ asitlerinin'),
        (r'lllşklll', 'ilişkili'),
        (r'h0kcrell 1 karsınornıarın', 'hücreli karsinomların'),
        (r'özelllklerl', 'özellikleri'),
        (r'arşı aşt,rıldıQında', 'karşılaştırıldığında'),
        (r'olasıtı~ı', 'olasılığı'),
        (r'en sı,k görülen', 'en sık görülen'),
        (r'HepatosellOler karsil\'\)oma, fıbrolameller varyant', 'Hepatosellüler karsinoma, fibrolameller varyant'),
        (r'Hepatosellüler karsinoma, şeffaf hücreli varyant', 'Hepatosellüler karsinoma, şeffaf hücreli varyant'),
        (r'Epitelioid hemanjioend~telyoma', 'Epitelioid hemanjiyoendotelyoma'),
        (r'Metastatik tümör \.', 'Metastatik tümör'),
        (r'Aşağıdaki ilaç~ardan hangisinin lityum atılımını arttırması m olasıdır\? ·',
         'Aşağıdaki ilaçlardan hangisinin lityum atılımını artırması en olasıdır?'),
        (r'\.Afağıdaki antimuskarlnlk ilaçlardan hangisi aşın aktif mesane, enürezJs ve nörojenlk mesane durumlannda tercih edilir\?',
         'Aşağıdaki antimuskarinik ilaçlardan hangisi aşırı aktif mesane, enürezis ve nörojenik mesane durumlarında tercih edilir?'),
        (r'T \'k \'d', 'Tropikamid'),
        (r'Disiklom\' ropı amı ın', 'Disiklomin'),
        (r'Hfyosiyamin', 'Hiyosiyamin'),
        (r'Bortezomlb temel etki mekanizması aşağıdakilerden hangisidir\?',
         'Bortezomib temel etki mekanizması aşağıdakilerden hangisidir?'),
        (r'265 proteazom lnh~bi~y~nu', '26S proteazom inhibisyonu'),
        (r'Mitokondriyal Bcl2 ınhıbısyonu', 'Mitokondriyal Bcl-2 inhibisyonu'),
        (r'PARP enzim lnhibisyonu', 'PARP enzim inhibisyonu'),
        (r'VEGFR· 1 kinaz lnhibisyonu', 'VEGFR-1 kinaz inhibisyonu'),
        (r'm TOR inhibisyonu', 'mTOR inhibisyonu'),
        (r'Maj&\' endlkasyonu d 6zelllkler1 ile 11 111 en ometr_ıyozis olan danazolun farmakolojlk \. \. g a,a\{ııdakl ifadelerden hangisi yanlıştır\?',
         'Majör endikasyonu endometriozis olan danazolün farmakolojik özellikleri ile ilgili aşağıdaki ifadelerden hangisi yanlıştır?'),
        (r'17 a-etinıl-testosteron to \. 1 reV1 ° up over fonksiyonlannı suprese eder\.',
         '17-alfa-etiniltestosteron türevi olup over fonksiyonlarını deprese eder.'),
        (r'Androjen v reV1 ° up over fonksiyonlannı suprese eder\.', 'Androjen ve progesteron reseptörlerine bağlanır.'),
        (r'Hemofili vee :=ron reseptörlerine ba~lanır\.', 'Hemofili ve idiyopatik trombositopenik purpura tedavisinde de kullanılır.'),
        (r'Aromataz enzimini ~~lk purpura tedavisinde de kullanılır\.', 'Aromataz enzimini inhibe eder.'),
        (r'hastalarda kullanımına O oke e~IQlnde~, ileri evre meme kansan', 'Meme kanserli hastalarda kullanımına onay verilmiştir.'),
        (r'Kilo alımı, ödem, llbidOd nay venlmlştlr\.', 'Kilo alımı, ödem, akne ve hirsutizm başlıca advers etkilerindendir.'),
        (r'llbidOd nay venlmlştlr\.', 'libidoda azalma başlıca advers etkilerindendir.'),
        (r'a azalma başlıca advers etklferindendır\.', ''),
        (r'Bakır_ Penisllamin', 'Bakır - Penisilamin'),
        (r'oımerkaprol', 'Dimerkaprol'),
        (r'Penisllamln', 'Penisilamin'),
        (r'ağır ~e a rı', 'ağır metal - antidot eşleştirmelerinden hangileri'),
        (r'doQrudur\?', 'doğrudur?'),
        (r'Otuz yaşınd~k! erkek hasta, ani başlayan sağ Yan ağrısı', 'Otuz yaşındaki erkek hasta, ani başlayan sağ yan ağrısı'),
        (r'Öyküs9rlden', 'Öyküsünden'),
        (r'öğrenili~or\.', 'öğreniliyor.'),
        (r's ~caklığı', 'sıcaklığı'),
        (r'37 ,2 °c', '37,2 °C'),
        (r'120/dakik~,', '120/dakika,'),
        (r'\.~olunum s_ayısı 24/daki~a', 'solunum sayısı 24/dakika'),
        (r'sağ kardiYıofrenik sinüsün \. kapalı olduğu görülüyor\.', 'sağ kardiyofrenik sinüsün kapalı olduğu görülüyor.'),
        (r'tetkiklerjnae 0-Dimer düzeyi yüksek buıu·nuyor\.', 'tetkiklerinde D-Dimer düzeyi yüksek bulunuyor.'),
        (r'Bu hastanın tanısı ·için aşağıdaki tetkiklerden hangisi lD\. uygundur\?',
         'Bu hastanın tanısı için aşağıdaki tetkiklerden hangisi en uygundur?'),
        (r'Torasik ultrasonografi \. \.', 'Torasik ultrasonografi'),
        (r'Ultrasonografı eşli~inde torasentez ve plevra sıvısının analizi', 'Ultrasonografi eşliğinde torasentez ve plevra sıvısının analizi'),
        (r'Toraks yüksek çözün0rlüklü bilgisayarlı tomografi ·', 'Toraks yüksek çözünürlüklü bilgisayarlı tomografi (HRCT)'),
        (r'Toraks bilgisayarlı tomografi anjtografı \. ·', 'Toraks bilgisayarlı tomografi anjiyografi (BT Anjiyo)'),
        (r'Bronkoskopl', 'Bronkoskopi'),
        (r'Aşağıdakllerden hang_lsi benign tiir der1 tümoriidilr\?', 'Aşağıdakilerden hangisi benign bir deri tümörüdür?'),
        (r'Dennatofibroı:n \.\.', 'Dermatofibrom'),
        (r'Baza1 hücreli karsinom', 'Bazal hücreli karsinom'),
        (r'Meme başı·nın :Paget ·hast~l :ığı', 'Meme başının Paget hastalığı'),
        (r'Skuamöz hücrelj karsinom', 'Skuamöz hücreli karsinom'),
        (r'Melanom', 'Melanom'),
        (r'Aıağıdakl rad YıQ izotoplard"an\. hangisi \.hem beta partikülü • • , • • em1Qı0nu lem i:le gama ,emisj on4 ~~p,ma özelllk18dnln olması nedenlJ:le teaavıae ltullanımının 1 yanı sıra görüntüleme amacıyla da kullanılıfr\?',
         'Aşağıdaki radyoizotoplardan hangisi hem beta partikülü emisyonu hem de gama emisyonu yapma özelliklerinin olması nedeniyle tedavide kullanımının yanı sıra görüntüleme amacıyla da kullanılır?'),
        (r'32P \(32-Fosfor\)', '32P (32-Fosfor)'),
        (r'1311 \(131-lyot\)', '131I (131-İyot)'),
        (r'89Sr: \(89-Stronslyum\)', '89Sr (89-Stronsiyum)'),
        (r'90y \(90-Yitriyum\)', '90Y (90-Yitriyum)'),
        (r'1898r \(~69-1:rBlyum\)', '186Re (186-Renyum)'),
        (r'sımetrılk tntraute·rln bOyOme kısıt1~1ığı •olan bebekler ile Ilgın aşığıda1d ifadelerden \'han,gls~ doğrudur\?',
         'Simetrik intrauterin büyüme kısıtlılığı olan bebekler ile ilgili aşağıdaki ifadelerden hangisi doğrudur?'),
        (r'~ ietal malnütr:isyoh !belifgindir\.', 'Fetal malnütrisyon belirgindir.'),
        (r'BJ Baş çevresi korunmuştur\.', 'Baş çevresi korunmuştur.'),
        (r'CJ Etiıolojide p\.lasental yetmezlik ön planda~~-', 'Etiyolojide plasental yetmezlik ön plandadır.'),
        (r'D\) lrıtmuterin \.büyüme kısıth·hğ·ı Olan OlguJar\.ın çoğunluğunu oluşturur\.', 'İntrauterin büyüme kısıtlılığı olan olguların çoğunluğunu oluşturur.'),
        (r'EJ ilk ttimesterdeki :koiıjenital \.enfeksiy~nl~r feta:I nedenler \.arasındadır\. ·', 'İlk trimesterdeki konjenital enfeksiyonlar fetal nedenler arasındadır.'),
        (r'Dfamond Blac an a ~ olasıdır\?', 'Diamond-Blackfan anemisiyle ilgili aşağıdaki ifadelerden hangisi yanlıştır?'),
        (r'Eritrositler makrosltlktlr\.', 'Eritrositler makrositiktir.'),
        (r'HbF dOzeyl artmıştır\.', 'HbF düzeyi artmıştır.'),
        (r'Eritrosit adenozln doam naz 1 düzeyi artmıştır\.', 'Eritrosit adenozin deaminaz (ADA) düzeyi artmıştır.'),
        (r'Bulgular ilk dekattan sonra başlar\.', 'Bulgular ilk dekattan sonra başlar.'),
        (r'RetikOloslt oranı azalmıştır\.', 'Retikülosit oranı azalmıştır.'),
        (r'Özellll<le sırta yayılan şiddetli kann ağrısı ile gelen ve 3 gün ö·nce blsiltletten düşme öyküsü olan 12 yaşındaki erkek hastada',
         'Özellikle sırta yayılan şiddetli karın ağrısı ile gelen ve 3 gün önce bisikletten düşme öyküsü olan 12 yaşındaki erkek hastada'),
        (r'Seksen yaşındaki diyabetik erkek hastada sabah erken saatıerd ıaparoskopik koles',
         'Seksen yaşındaki diyabetik erkek hastada sabah erken saatlerde laparoskopik kolesistektomi yapılıyor. Postoperatif dönemde idrar yapamama ve suprapubik ağrı gelişen hastada en olası tanı aşağıdakilerden hangisidir?'),
        (r'Oriner retansiyon', 'Üriner retansiyon'),
        (r'lntraabdominal apse', 'İntraabdominal apse'),
        (r'Antikoagülanlar ve acil durumlarda antikoagülan etkinin geri dönüşümü için kullanılabilecek ajanlarla ilglll aşağıdaki eşleştirmelerden hangisi',
         'Antikoagülanlar ve acil durumlarda antikoagülan etkinin geri dönüşümü için kullanılabilecek ajanlarla ilgili aşağıdaki eşleştirmelerden hangisi yanlıştır?'),
        (r'Varfarin -- K vitamini', 'Varfarin - K vitamini'),
        (r'Dabigatran - Desmopressln', 'Dabigatran - Desmopresin'),
        (r'Primer sklerozan kolanjit \(PSK\) tanı ve tedavisi ile ilgili aşaöıdaki ifadelerden hangisi yanlıştır\?',
         'Primer sklerozan kolanjit (PSK) tanı ve tedavisi ile ilgili aşağıdaki ifadelerden hangisi yanlıştır?'),
        (r'Yorgunluk, kaşıntı ve sarılık h~staların başvuru n7denle~ndendir\.', 'Yorgunluk, kaşıntı ve sarılık hastaların başvuru nedenlerindendir.'),
        (r'lnflamatuvar bağırsak hastalıgı ~!anlarda,\. k_aracığer enzimlerinde bozulma varlığında PSK tanısı duş0n0lmelıdır\.',
         'İnflamatuvar bağırsak hastalığı olanlarda karaciğer enzimlerinde bozulma varlığında PSK tanısı düşünülmelidir.'),
        (r'ERCP\'deki görüntü erken tanı koydurucudur\.', 'ERCP\'deki görüntü erken tanı koydurucudur.'),
        (r'Oıseratif kolitle kolektomi PSK\'nin ilerlemesini durdurur\.', 'Ülseratif kolitte kolektomi PSK\'nin ilerlemesini durdurur.'),
        (r'Transplantasyon yapılan hastalarda PSK tekrarlayabileceğinden tekrar transplantasyon gerekebilir\.',
         'Transplantasyon yapılan hastalarda PSK tekrarlayabileceğinden tekrar transplantasyon gerekebilir.'),
        (r'Total tiroidektomi cerrahisi sonrası en sık görülen komplikasyon aşağıdakilerden hangisidir\? \.',
         'Total tiroidektomi cerrahisi sonrası en sık görülen komplikasyon aşağıdakilerden hangisidir?'),
        (r'Rekürren laringeal sinir hasarı', 'Rekürren laringeal sinir hasarı'),
        (r'Superior laringeal sinir hasarı •', 'Superior laringeal sinir hasarı'),
        (r'Pnömotoraks', 'Pnömotoraks'),
        (r'Geçici hipoparatiroidizm ·', 'Geçici hipoparatiroidizm'),
        (r'Duktus torasikus yaralanması', 'Duktus torasikus yaralanması'),
        (r'Elli iki yaşındaki erkek hastada, travma nedeniyle Treltz ll~amanının 30 cm attından 1 metre uzunlu~unda jejunum segmentl eksıze ediliyor\. AşaQıdakllerden hangisinin bu hastada ileride kısa baOırsak sendromu gelişme riskini artırması ın aı olasıdır\?',
         'Elli iki yaşındaki erkek hastada, travma nedeniyle Treitz ligamanının 30 cm altından 1 metre uzunluğunda jejunum segmenti eksize ediliyor. Aşağıdakilerden hangisinin bu hastada ileride kısa bağırsak sendromu gelişme riskini artırması en az olasıdır?'),
        (r'~ diks perforasyonu nedeniyle ~erminal ileumu içeren segmentaı rezeksiyon \. \.',
         'Apendiks perforasyonu nedeniyle terminal ileumu içeren segmental rezeksiyon'),
        (r'ikinci kez ince bağırsak rezeksıyonu sonucu top_lamda 225 cm ince l\)ağırsak kalm~sı \.',
         'İkinci kez ince bağırsak rezeksiyonu sonucu toplamda 225 cm ince bağırsak kalması'),
        (r'Total kolektomi \.yapılması', 'Total kolektomi yapılması'),
        (r'l:fsstanın Crohn hastalığı tanfsi\' aıma~ı', 'Hastanın Crohn hastalığı tanısı alması'),
        (r'Son 2/311ük distal ileumun Ve termirial i18umun rezeksiyonu', 'Son 2/3\'lük distal ileumun ve terminal ileumun rezeksiyonu'),
        (r'Direkt ve lndlrekt lngulnaı hernllerln ayrımınd · anatomik yapı aıaOıdakllerden hangisidir\? 8 kullanılan referans',
         'Direkt ve indirekt inguinal hernilerin ayrımında kullanılan referans anatomik yapı aşağıdakilerden hangisidir?'),
        (r'Musculus rectus abdomlnls lateral kenarı', 'Musculus rectus abdominis lateral kenarı'),
        (r'lnferlor eplgastrlk arter ve ven', 'İnferior epigastrik arter ve ven'),
        (r'lngulnal llgaman', 'İnguinal ligaman'),
        (r'Medlan umbllikal ligaman', 'Median umbilikal ligaman'),
        (r'Pektlneal \(Cooper\) llgaman', 'Pektineal (Cooper) ligaman'),
        (r'Aksesuar dalaQın ııııı\.\.\. \.\.\. bulunduQu lokallzaayon apC,ıclalcll _ rden hangisidir\?',
         'Aksesuar dalağın en sık bulunduğu lokalizasyon aşağıdakilerden hangisidir?'),
        (r'Pankreas kuyruQu arkas ı', 'Pankreas kuyruğu arkası'),
        (r'Mezenter', 'Mezenter'),
        (r'Splenlk hllus', 'Splenik hilus'),
        (r'BOyOk omentum', 'Büyük omentum'),
        (r'Splenokollk llgaman', 'Splenokolik ligaman'),
        (r'Nöroaksiyel blok yapılırken orta hatta J\.lk\. geçilen llgaman aşağıdakilerden hangisidir\?',
         'Nöroaksiyel blok yapılırken orta hatta ilk geçilen ligaman aşağıdakilerden hangisidir?'),
        (r'Sapraspinöz llgaman', 'Supraspinöz ligaman'),
        (r'lntersplnöz llgaman', 'İnterspinöz ligaman'),
        (r'Ligamentum flavum', 'Ligamentum flavum'),
        (r'\) Anterior longitudinal llgaman', 'Anterior longitudinal ligaman'),
        (r'Posterior longitudinal ligaman', 'Posterior longitudinal ligaman'),
        (r'bronkore ve bronko p zm görOlmesl \. 1 8 radlkardl 1',
         'Aşağıdaki ajanlara bağlı zehirlenmelerin hangisinde bradikardi, bronkore ve bronkospazm görülmesi en olasıdır?'),
        (r'· Oploidl~r', 'Opioidler'),
        (r'Beta blokörler', 'Beta blokörler'),
        (r'oıgoksın', 'Digoksin'),
        (r'Trtslklik antıdepre anlar', 'Trisiklik antidepresanlar'),
        (r'Organofosfatlar', 'Organofosfatlar'),
        (r'Hipertro örülmesi d iğe rlerinden !ı!a~a - _ x ,, hangisinin g',
         'Hipertrofik pilor stenozu olan bir çocukta aşağıdakilerden hangisinin görülmesi diğerlerinden daha az olasıdır?'),
        (r'Safralı kusma', 'Safralı kusma'),
        (r'Fışkırır tarzda kusnıa', 'Fışkırır tarzda kusma'),
        (r'Bulantı', 'Bulantı'),
        (r'Çilek renginde kusma', 'Çilek renginde kusma'),
        (r'Olsfajl', 'Disfaji'),
        (r'Oç gündür ~kut sinüzit semptomla rı olan 10 bllateral orbıtal aO rı, kemoz ıs ve propt \. \. Yaşındaki erkek hastad \. parallzisi gelişiyor\. \' ozıs ıle 3, 4, 5 ve 6\. kraniyaı sin~; su hasta için en ola\'s ı tanı aşa\.ır\. ıda kll d ~ er · en hangi ldlr\?',
         'Üç gündür akut sinüzit semptomları olan 10 yaşındaki erkek hastada bilateral orbital ağrı, kemozis ve proptozis ile 3, 4, 5 ve 6. kraniyal sinir paralizisi gelişiyor. Bu hasta için en olası tanı aşağıdakilerden hangisidir?'),
        (r'Preseptal sel0llt · 9', 'Preseptal selülit'),
        (r'Orbltal selülit', 'Orbital selülit'),
        (r'Orbital a~se', 'Orbital apse'),
        (r'KavemOz slnUs trombofleblti', 'Kavernöz sinüs tromboflebiti'),
        (r'Subperiostalapse', 'Subperiosteal apse'),
        (r'Yirmı ~ş Y:ruyor\. Hastanın kan grubunun A Rh {\-\), eşinin kan Qrutıo 01 A Rh \+ o \., \- \., •ı· nrn AntHJ lgG titreSinin 1/4 oldugu ogrenı ıyor\. Bu gebe için bir sonraki aşam_a~~ yapılması önerilen en UVgug yaklaşım aşağı~akilerden hangısıdır\?',
         'Yirmi beş yaşındaki gebe hastanın kan grubunun A Rh (-), eşinin kan grubunun ise A Rh (+) olduğu ve Anti-D IgG titresinin 1/4 olduğu öğreniliyor. Bu gebe için bir sonraki aşamada yapılması önerilen en uygun yaklaşım aşağıdakilerden hangisidir?'),
        (r'Patemal zigosite tayini \.', 'Paternal zigosite tayini'),
        (r'Anti-D immunoglobulin verilmesi', 'Anti-D immünoglobulin verilmesi'),
        (r'Matemal zigosite tayini •', 'Maternal zigosite tayini'),
        (r'Amniotik sıvıda bilirubin ölçümü', 'Amniyotik sıvıda bilirubin ölçümü'),
        (r'Koryon villus örnekleme ile fetal genotip tayini', 'Koryon villus örneklemesi ile fetal genotip tayini'),
        (r'ı\. Dinlenme hAllnde semptom yoktur\. il\. Evin içinde bir odadan dtaer odaya yürürken çabuk yorulma çarpıntı, dlspne gibi şikayetler olur\. \' 111\. Merdiven inerken semptom yoktur\. · • Yukandakllerden hangllerl, 11Gebelikte Kalp Hastalıkları NYHA \(New York Heart Assoclatlon\) Fonksiyonel Sınıflaması"na göre sınıf 111 semptomlar ile uyumludur\?',
         'I. Dinlenme halinde semptom yoktur.\nII. Evin içinde bir odadan diğer odaya yürürken çabuk yorulma, çarpıntı, dispne gibi şikayetler olur.\nIII. Merdiven inerken semptom yoktur.\n\nYukarıdakilerden hangileri, "Gebelikte Kalp Hastalıkları NYHA (New York Heart Association) Fonksiyonel Sınıflaması"na göre Sınıf III semptomlar ile uyumludur?'),
    ]
    
    for pat, rep in replaces:
        t = re.sub(pat, rep, t, flags=re.IGNORECASE)
        
    # Strip residual garbage
    t = re.sub(r'[\~µ_#§\<\>\\{}]', '', t)
    t = re.sub(r'\s{2,}', ' ', t).strip()
    return t

print("Sanitization module compiled.")
